### ISSUE TITLE
How to record salinity data on RBR floats reporting two salinity channels

### ISSUE THREAD

**Issue by mscanderbeg** [OneArgo/ADMT#30]
Form a working group to recommend how to record salinity data on RBR floats reporting two salinity channels:  onboard corrected salinity and raw, uncorrected salinity.  Report proposal at AST-25.

**Comment by apswong** [comment]
A working group that consisted of @matdever, @apswong, Deb West-Mack and Susan Wijffels discussed this issue and agreed on a set of processing pathways, which were described in this flowchart.
[RBR_Scor_decision_tree.pdf](https://github.com/OneArgo/ADMT/files/14183929/RBR_Scor_decision_tree.pdf)
