### ISSUE TITLE
Send email to AST asking for any concerns about including PI_NAME in NVS server.  If no concerns are raised after a week, accept proposal for controlling PI_NAME.

### ISSUE THREAD

**Issue by cgourcuf** [OneArgo/ADMT#4]

**Comment by cgourcuf** [comment]
@mscanderbeg this action was already done, I just created it as a test :-).

**Comment by mscanderbeg** [comment]
This action has been done.  An email was sent on November 9th, 2023 and AST was given a week to send concerns.  None were sent, so the NVS table for controlling PI_NAME has been made live.
