### ISSUE TITLE
Table R03 change the fill value of LED_FLASHING_COUNT_DOXY into NC_FILL_DOUBLE

### ISSUE THREAD

**Issue by tcarval** [OneArgo/ADMT#74]
Message from Catherine Schmechtig on 12/09/2024
_There was an inconsistency between the fill value for the LED_FLASHING_COUNT_DOXY  and its type,
so I changed the Fill value to NC_FILL_DOUBLE, and send the updated definition file for the file checker 
This change may affect mainly the jamstec dac for the Rinko sensor._

- [x] The table R03 is updated to implement that change.
- [x] The information is posted on http://www.argodatamgt.org/Data-Mgt-Team/News/Argo-physical-parameters-list-updated10
- [x] The file format checker is updated on Coriolis GDAC
- [x] The file format checker is updated on US GDAC

A sample file : [BR6990661_006.zip](https://github.com/user-attachments/files/16991414/BR6990661_006.zip)

**Comment by tcarval** [comment]
The JMA DAC has 10 floats reporting LED_FLASHING_COUNT_DOXY parameter.
One of them is still active: https://fleetmonitoring.euro-argo.eu/float/7900875
The new version of R03 LED_FLASHING_COUNT_DOXY would be blocked by the format checker.
I'll wait for a JMA green light before updating the format checker.

**Comment by ksato-aopc** [comment]
Thank you for contacting me. I have asked JMA when they will complete their response to this format change and am waiting their reply. I will contact you when I receive it.

**Comment by Argo-JMA** [comment]
Concerning the "LED_FLASHING_COUNT_DOXY", JMA are working on updating our data processing.
Could you please check a sample file we made? 
[BR7900875_027.zip](https://github.com/user-attachments/files/17025741/BR7900875_027.zip)

We would like to know whether the "LED_FLASHING_COUNT_DOXY:_FillValue" is appropriate. Thank you.

**Comment by tcarval** [comment]
Thank you for the sample file.
There is one error for the format checker :
    <error>attribute: LED_FLASHING_COUNT_DOXY:_FillValue: Definitions differ 
	Specification = '9.969209968386869E36'
	Data File     = '9.96920996838687E36'</error>
  </errors>

Here is the filechecker full report: 
[BR7900875_027.nc.zip](https://github.com/user-attachments/files/17028683/BR7900875_027.nc.zip)

In your code, you should probaby use the NC_FILL_DOUBLE fill value.

**Comment by Argo-JMA** [comment]
Thank you for your kind support.
Could you please check an updated sample file?
[BR7900875_027.zip](https://github.com/user-attachments/files/17039845/BR7900875_027.zip)

"_FillValue" is 9.969209968386869e+36 this time.

**Comment by tcarval** [comment]
Excellent, the file passed the format check 🙂
Could you tell me when I can update the operationnal  format checker to accept the files on GDAC ?

```
<FileCheckResults filechecker_version="v2.8.01" spec_version="-r1259">
  <file>/home/idmtmp7/tcarval/argo/in/BR7900875_027.nc</file>
  <status>FILE-ACCEPTED</status>
  <phase>FILE-NAME-CHECK</phase>
  <metadata>
    <dac>jma</dac>
    <DATA_TYPE>B-Argo profile</DATA_TYPE>
    <FORMAT_VERSION>3.1 </FORMAT_VERSION>
    <DATE_UPDATE>20240918053059</DATE_UPDATE>
    <DATA_CENTRE> JA,JA</DATA_CENTRE>
    <PLATFORM_NUMBER> 7900875,7900875</PLATFORM_NUMBER>
    <PI_NAME> JAMSTEC,JAMSTEC</PI_NAME>
    <WMO_INST_TYPE> 864,864</WMO_INST_TYPE>
    <DATA_MODE>AR</DATA_MODE>
    <DIRECTION>AA</DIRECTION>
    <N_PROF>2</N_PROF>
    <N_LEVELS>1314</N_LEVELS>
    <CYCLE_NUMBER> 027,027</CYCLE_NUMBER>
    <JULD-dtg> 20240914124013,20240914124013</JULD-dtg>
    <LATITUDE> 34.4530,34.4530</LATITUDE>
    <LONGITUDE> 176.9110,176.9110</LONGITUDE>
    <JULD_QC>11</JULD_QC>
    <POSITION_QC>11</POSITION_QC>
    <PROFILE_TEMP_QC>null</PROFILE_TEMP_QC>
    <PROFILE_PSAL_QC>null</PROFILE_PSAL_QC>
    <PROFILE_DOXY_QC>A </PROFILE_DOXY_QC>
    <STATION_PARAMETERS>PRES DOXY COUNT_DOXY LED_FLASHING_COUNT_DOXY TEMP_DOXY TEMP_COUNT_DOXY</STATION_PARAMETERS>
    <PARAMETER_DATA_MODE>RARRRR</PARAMETER_DATA_MODE>
  </metadata>
  <errors number="0"/>
  <warnings number="0"/>
</FileCheckResults>
```


[BR7900875_027.nc.zip](https://github.com/user-attachments/files/17040610/BR7900875_027.nc.zip)

**Comment by Argo-JMA** [comment]
Happy to hear that! Now we could say anytime would be OK.  
Just let me know when you update the operational format checker.
JMA will update our data processing codes in a timely manner.

**Comment by tcarval** [comment]
Good, I update it right now and inform US GDAC. I let you know when it is ready.

**Comment by tcarval** [comment]
The filechecker is updated in Coriolis GDAC site.
I ask the USGADC to update it.
https://github.com/euroargodev/ArgoNetCDF/releases/tag/v2.8.12

**Comment by tcarval** [comment]
Both GDACs now accept the R03 update for LED*DOXY.
@Argo-JMA you can now distribute the rinko oxygen files.

**Comment by Argo-JMA** [comment]
Thanks you all!
JMA updated our data processing codes.
